---
- name: Configurar servidor de banco de dados
  hosts: db01

  user: vagrant
  become: true
  vars_files:
    - vars/main.yaml
  vars:
    - dbname: "db_api_rest"
    - dbusername: "root"
    - dbpassword: "devopsmaonamassa"  
  roles: 
    - configuracao-default-so
    - role: geerlingguy.mysql