Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus   = "1"
  end
  config.vm.provision "shell", inline: "echo Config docker swarm cluster"
  config.vm.define "manager" do |manager|
    manager.vm.box = "centos/7"
    manager.vm.hostname = "manager"
    manager.vm.provision "shell", path: "provision.sh"
    manager.vm.network "private_network", ip: "192.168.4.2"
    manager.vm.network "forwarded_port", guest: 80, host: 8090
    manager.vm.synced_folder ".", "/vagrant", type: "nfs"
  end

  config.vm.define "worker1" do |worker1|
      worker1.vm.box = "centos/7"
      worker1.vm.hostname = "worker1"
      worker1.vm.provision "shell", path: "provision.sh"
      worker1.vm.network "private_network", ip: "192.168.4.3"
      worker1.vm.synced_folder ".", "/vagrant", type: "nfs"
  end
  config.vm.define "worker2" do |worker2|
      worker2.vm.box = "centos/7"
      worker2.vm.hostname = "worker2"
      worker2.vm.provision "shell", path: "provision.sh"
      worker2.vm.network "private_network", ip: "192.168.4.4"
      worker2.vm.synced_folder ".", "/vagrant", type: "nfs"
  end
end