Vagrant.configure("2") do |config|  
  config.vm.box = "centos/7"  
  config.vm.hostname = "control-node"  
  #config.vm.network :private_network, ip: "192.168.4.2", name: "HostOnly", virtualbox__intnet: true 
  config.vm.network :private_network, ip: "192.168.4.12" 
  #config.vm.network :private_network, type: "dhcp" 
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provision "shell", path: "provision.sh"
  #config.vm.network "private_network", ip: "10.0.1.12" 
  #config.vm.network "private_network", type: "dhcp"
end
