
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  #config.vm.provider "hyperv"
  config.vm.hostname = "docker"
  config.vm.network :private_network, ip: "192.168.4.20"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provision "shell", path: "provision.sh"
end
