mysql_root_password: devopsmaonamassa
mysql_databases:
  - name: db_api_rest
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: notesapp
    host: "%"
    password: devopsmaonamassa
    priv: "notes.*:ALL"