Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "sonarqube"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.network "forwarded_port", guest: 9000, host: 9000, hostip:'127.0.0.1'
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus   = "1"
  end

end